version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: 1
    command: pytest
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:mysecretpassword@db:5432/test
      UVICORN_PORT: 8080
      TTS_ENGINE_URL: http://host.docker.internal:3000
      ENV: test
    env_file:
      - .env
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: 1
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      UVICORN_PORT: 8080
      TTS_ENGINE_URL: http://host.docker.internal:3000
      ENV: dev
    env_file:
      - .env
    volumes:
      - .:/app

  # Supabase services
  # studio:
  #   image: supabase/studio:20231114-1442e42
  #   ports:
  #     - 8082:8082
  
  # auth:
  #   image: supabase/gotrue:v2.114.1
  #   environment:
  #     - GOTRUE_SMTP_USER=
  #     - GOTRUE_SMTP_PASS=

  # mail:
  #   container_name: supabase-mail
  #   image: inbucket/inbucket:3.0.3
  #   ports:
  #     - '2500:2500' # SMTP
  #     - '9000:9000' # web interface
  #     - '1100:1100' # POP3

  db:
    image: supabase/postgres:15.1.0.117
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db-init/99_create_test_db.sql:/docker-entrypoint-initdb.d/99_create_test_db.sql

volumes:
  db-data:
