"""add table for voice presets.

Revision ID: 12d594f0946d
Revises: 99aaaa438629
Create Date: 2023-12-07 14:58:12.749313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d594f0946d'
down_revision = '99aaaa438629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_preset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('voice_preset_pkey')),
    sa.UniqueConstraint('name', name=op.f('voice_preset_name_k'))
    )
    op.add_column('tts_transcription', sa.Column('voice_preset_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('tts_transcription_voice_preset_id_fkey'), 'tts_transcription', 'voice_preset', ['voice_preset_id'], ['id'])
    op.drop_column('tts_transcription', 'voice_preset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tts_transcription', sa.Column('voice_preset', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('tts_transcription_voice_preset_id_fkey'), 'tts_transcription', type_='foreignkey')
    op.drop_column('tts_transcription', 'voice_preset_id')
    op.drop_table('voice_preset')
    # ### end Alembic commands ###
