"""add base64 column to voice preset.

Revision ID: 262929c3cfb6
Revises: 12d594f0946d
Create Date: 2023-12-15 09:38:18.500850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262929c3cfb6'
down_revision = '12d594f0946d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_preset', sa.Column('base64', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_preset', 'base64')
    # ### end Alembic commands ###
