"""Add user_exists function.

Revision ID: 29033ae4a562
Revises: e52caf0bd042
Create Date: 2023-11-17 15:49:23.243985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29033ae4a562'
down_revision = 'e52caf0bd042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION email_exists(email_address text)
        RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
        DECLARE
        exists_flag boolean;
        BEGIN
        SELECT EXISTS(
        SELECT 1
        FROM auth.users
        WHERE email = email_address
        ) INTO exists_flag;

        RETURN exists_flag;
        END;
        $$;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION email_exists(text);")
    # ### end Alembic commands ###
