"""Initial.

Revision ID: e52caf0bd042
Revises: 
Create Date: 2023-11-17 15:48:01.465940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52caf0bd042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        """
    )
    op.create_table(
        'user',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('uuid_generate_v4()')),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('supabase_uid', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    )
    op.execute('ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;')
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=True)
    op.create_index(op.f('user_supabase_uid_idx'), 'user', ['supabase_uid'], unique=True)
    op.create_table(
        'tts_transcription',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('voice_preset', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('audio', sa.LargeBinary(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('tts_transcription_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('tts_transcription_pkey')),
    )
    op.execute('ALTER TABLE tts_transcription ENABLE ROW LEVEL SECURITY;')
    op.execute(
        'ALTER TABLE alembic_version ENABLE ROW LEVEL SECURITY;'
    )  # Make sure alembic_version is not accessible to Supabase anonymous users
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tts_transcription')
    op.drop_index(op.f('user_supabase_uid_idx'), table_name='user')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
