"""remove language column from user.

Revision ID: fdb2eab5fdc1
Revises: 99aaaa438629
Create Date: 2023-11-20 10:15:37.878313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb2eab5fdc1'
down_revision = '99aaaa438629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
